version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: todoapp-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_user -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 5

  todoapp-backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: todoapp-backend
    restart: always
    ports:
        - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasks
        SPRING_DATASOURCE_USERNAME: task_user
        SPRING_DATASOURCE_PASSWORD: task_password
        SERVER_PORT: "8080"

volumes:
  postgres_data:
